version: '3'
services:
    web:
        build: .
        ports:
            - 5000:5000
        volumes:
            - .:/solar_charge_controller
        # links: redis
        # depends_on: 
        #     - redis
        #     - mongodb
    
    # redis:
    #     image: redis
